fix bug in -v and remove unnecessary file conversion

diff --git a/pli-dep/mypli b/pli-dep/mypli
--- a/pli-dep/mypli
+++ b/pli-dep/mypli
@@ -27,30 +27,14 @@ done
 
 export STEPLIB=FULTONM.PORT.TEMPV6R2:$STEPLIB
 if ${version} ; then
-  cd /tmp; echo " PLIVER: PROC OPTIONS(MAIN);" >$$.pli;  pli -qlist -qnc -c $$.pli >/dev/null 2>/dev/null ; cat $$.lst | head -1; rm $$.lst $$.pli
-  exit 0
+  (cd /tmp; echo " PLIVER: PROC OPTIONS(MAIN);" >$$.pli;  pli -qlist -qnc -c $$.pli >/dev/null 2>/dev/null ; cat $$.lst | head -1; rm $$.lst $$.pli)
 fi
   
 if [ "${src}x" = "x" ]; then
-  echo "Unable to determine source file from command line $@" >&2
-  exit 8
-fi
-
-
-cp=$(chtag -p "${src}" | awk '{ print $2; }')
-
-if [ "${cp}x" = "ISO8859-1x" ]; then
-  if ! a2e "${src}" ; then
-    echo "PL/I file is in ASCII and needs to be converted to EBCDIC, but conversion failed" >&2
+  if ! ${version}; then
+    echo "Unable to determine source file from command line $@" >&2
     exit 8
   fi
 fi
+
 pli ${pliopts} $src
-rc=$?
-
-if [ "${cp}x" = "ISO8859-1x" ]; then
-  if ! e2a "${src}" ; then
-    echo "Conversion of PL/I file back to ASCII failed" >&2
-    exit 8
-  fi
-fi
