wrote up the tests and - found a bug! - which is nice

diff --git a/test/testXsysvar b/test/testXsysvar
--- a/test/testXsysvar
+++ b/test/testXsysvar
@@ -7,13 +7,10 @@
 # 4) verify 2 records exist - initial 'dummy' record and one fixed value record
 
 # 5) create the sysvar with value of length 16, and verify it can be read correctly and there are now 3 records
-# - create the sysvar with value of length 32, and verify it can be read correctly and now there are 4 records
-# - create the sysvar with length 31 down to 0 and verify there are still 4 records
+# 6) create the sysvar with value of length 32, and verify it can be read correctly and now there are 4 records
+# 7) create the sysvar with length 0 to 32 and verify there are still 4 records
 #
-# - create a set of sysvar names with key of length 1 to 15 with short values
-# - create a set of sysvar names with key of length 16 to 32 with short values
-# - create a set of sysvar names with key of length 1 to 15 with long values
-# - create a set of sysvar names with key of length 16 to 32 with long values
+# 8) create a set of sysvar names with key of length 1 to 32 with values of length 0 to 31
 
 dhlq='ibmuser.xsysvar'
 
@@ -93,3 +90,87 @@ if [ ${records} -ne 3 ]; then
 	exit 8
 fi
 
+#
+# (6)
+#
+value="${value}${value}"
+Xsysvar -D${dhlq} "${key}=${value}"
+rc=$?
+if [ $rc -gt 0 ]; then
+	echo "Failed on 'longer set': ${key}=${value}" >&2
+	exit 8
+fi
+out=`Xsysvar -D${dhlq} "${key}"`
+rc=$?
+if [ $rc -gt 0 ]; then
+	echo "Failed on 'longer get': ${key} (Expecting <${value}>)" >&2
+	exit 8
+fi
+if [ "${out}" != "${value}" ]; then	
+	echo "Failed on 'longer get': ${key} (Expecting <${value}> but got <${out}>)" >&2
+	exit 8
+fi
+
+records=`vsamrepro ${dhlq} /dev/null | grep IDC0005I | awk ' { print $7; }'`
+if [ ${records} -ne 4 ]; then
+	echo "Expected 4 records after longer 'set' but there were ${records}" >&2
+	exit 8
+fi
+
+#
+# (7)
+#
+value=''
+
+while [ ${#value} -lt 33 ]; do
+	Xsysvar -D${dhlq} "${key}=${value}"
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "Failed on 'short set': ${key}=${value}" >&2
+		exit 8
+	fi
+	out=`Xsysvar -D${dhlq} "${key}"`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "Failed on 'short get': ${key} (Expecting <${value}>)" >&2
+		exit 8
+	fi
+	if [ "${out}" != "${value}" ]; then	
+		echo "Failed on 'short get': ${key} (Expecting <${value}> but got <${out}>)" >&2
+		exit 8
+	fi
+	value="1${value}"
+done
+
+records=`vsamrepro ${dhlq} /dev/null | grep IDC0005I | awk ' { print $7; }'`
+if [ ${records} -ne 4 ]; then
+	echo "Expected 4 records after short/medium/long/longer 'sets' but there were ${records}" >&2
+	exit 8
+fi
+
+#
+# (7)
+#
+key='K'
+value=''
+
+while [ ${#key} -lt 33 ]; do
+	Xsysvar -D${dhlq} "${key}=${value}"
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "Failed on 'key set': ${key}=${value}" >&2
+		exit 8
+	fi
+	out=`Xsysvar -D${dhlq} "${key}"`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "Failed on 'key get': ${key} (Expecting <${value}>)" >&2
+		exit 8
+	fi
+	if [ "${out}" != "${value}" ]; then	
+		echo "Failed on 'key get': ${key} (Expecting <${value}> but got <${out}>)" >&2
+		exit 8
+	fi
+	key="${key}-"
+	value="${value}%"
+done
