add new function automntzfs to update the IPL entries for mount

diff --git a/volume/volfunc b/volume/volfunc
--- a/volume/volfunc
+++ b/volume/volfunc
@@ -226,15 +226,81 @@ mntzfs() {
 }
 
 #
-# automntzfs: add the file system so it will be mounted on IPL the same way it is currently mount
-#             a backup file will be written to $TMPDIR/<member> of the original file
+# automntzfs: add the file system so it will be mounted on IPL the same way it is currently mounted
+#             a backup file will be written to $TMPDIR/<member> of the original file (/tmp used if TMPDIR not set)
+#
+# New entry written to BPXPRMxx will be of the form:
+#  MOUNT FILESYSTEM('<ds>')
+#        MOUNTPOINT('<dir>')
+#        TYPE(ZFS) MODE(<mode>)
 #
 automntzfs() {
+#set -x
         if [ $# -ne 2 ]; then
 	        echo "Syntax: automntzfs <xx> <directory>" >&2
 	        echo "automntzfs requires 'xx' of BPXPRMxx member to be updated and <directory> of already mounted file system" >&2
                 return 8
 	fi
+        sfx=$(echo ${1} | tr '[:lower:]' '[:upper:]')
+        dir="${2}"
+	
+	if ! mount_details=$( df "${dir}" ) ; then 
+		echo "Unable to find ${dir}. Is it mounted?" >&2
+		return 16
+	fi
+	if ! mount_verbose=$( df -v "${dir}" ) ; then
+		echo "Unable to get verbose information for mount point ${dir}" >&2
+		return 16
+	fi
+	mount_type=$( echo "${mount_verbose}" | head -3 | tail -1 | tr ',' ' ' | awk '{print $2; }' )
+	case $mount_type in 
+		Read) mode='READ';;
+		Read/Write) mode='RDWR';;
+		*) echo "Unexpected mount type of ${mount_type}. No action performed" >&2; return 16;;
+	esac
+	mnt_ds=$( echo "${mount_details}" | tail -1 | tr "()" "  " | awk ' { print $2 }' )
+	
+	tmpdir=${TMPDIR:-/tmp}
+	mem="BPXPRM${sfx}"
+	if ! parmlib_ds=$( parmwhence "${mem}" ) ; then
+		echo "Dataset member ${mem} is not in the parmlib concatenation. No action performed" >&2
+		return 16
+	fi
+	mountline_1="MOUNT FILESYSTEM('${mnt_ds}')"
+	mountline_2="      MOUNTPOINT('${dir}')"
+	mountline_3="      TYPE(ZFS) MODE(${mode})"
+
+	dsmem="${parmlib_ds}(${mem})"
+	tmpfile="${tmpdir}/${parmlib_ds}(${mem})"
+	if ! dcp "${dsmem}" "${tmpfile}" ; then
+		echo "Unable to make backup copy of ${dsmem} to ${tmpfile}. No action performed" >&2
+		return 16
+	fi
+	if grep "${mountline_1}" "${tmpfile}" >/dev/null ; then
+		echo "There is already an entry for dataset ${mnt_ds} in ${dsmem}. No action performed" >&2
+		rm "${tmpfile}"
+		return 16
+	fi	
+
+	if ! decho -a "${mountline_1}
+${mountline_2}
+${mountline_3}" "${dsmem}" ; then
+		echo "Failure trying to update ${dsmem}. Backup copy of original is at ${tmpfile}" >&2
+		return 32
+	fi	
+
+	if ! check_parmlib=$( opercmd "SETOMVS SYNTAXCHECK=(${sfx})" ) ; then
+		echo "Unable to issue SETOMVS SYNTAXCHECK on ${mem}. Validate dataset before IPL. Backup copy of original is at ${tmpfile}" >&2
+		echo "${check_parmlib}" >&2
+		return 16
+	fi
+	if ! $( echo "${check_parmlib}" | grep BPXO039I >/dev/null ) ; then
+		echo "Possible failure in SETOMVS SYNTAXCHECK on ${mem}. Validate dataset before IPL. Backup copy of original is at ${tmpfile}" >&2
+		echo "${check_parmlib}"	>&2
+		return 16
+	fi
+	rm -f "${tmpfile}"
+	return 0
 }
 
 echo 'Functions: '
